-- GERADO POR scripts/gerar_seed.py — NÃO EDITAR À MÃO.
-- Para alterar, edite o script (ou o CSV) e rode: python scripts/gerar_seed.py
-- Fonte: Cópia de Casamento - Convidados.csv
-- 113 convidados · 104 buscáveis no site · 5 já confirmados
-- Rodar no SQL Editor do Supabase, depois de 02_rls.sql.
-- Recria a lista do zero; confirmações feitas pelo site são perdidas.

delete from convidados;

insert into convidados (nome, confirmacao, visivel)
values
  ('Rosana Gardenal Antoneli', NULL, true),
  ('Gerson Antoneli', NULL, true),
  ('Gabriela Gardenal Antoneli', NULL, true),
  ('Pedro Bonomo', NULL, true),
  ('Rafael Gardenal Antoneli', NULL, true),
  ('Bruna Pessoa', NULL, true),
  ('Mourad Ali Mourad', NULL, true),
  ('Andrea Eliane de Oliveira Mourad', NULL, true),
  ('Rhamza Mourad Mourad', NULL, true),
  ('Jafar Mourad Mourad', NULL, true),
  ('Maria Eduarda Guedes', NULL, true),
  ('Gislaine Antoneli', NULL, true),
  ('Fabio Calegari', NULL, true),
  ('Theo Antoneli Calegari', 'pago', true),
  ('Divanil Antoneli', NULL, true),
  ('Sabrina Antoneli Calegari', NULL, true),
  ('Mauricio Guadrini Gardenal', NULL, true),
  ('Suzel Valle Gardenal', NULL, true),
  ('Mariana Valle Gardenal', NULL, true),
  ('Gilson Santos Jr', NULL, true),
  ('Marina Valle Gardenal', NULL, true),
  ('Henrique Candido', NULL, true),
  ('Maiara Valle Gardenal', NULL, true),
  ('Marcos Guadrini Gardenal', NULL, true),
  ('Roberta Gardenal', NULL, true),
  ('Alessandro Oswaldo Ribeiro Pires', NULL, true),
  ('Sumaia de Oliveira Thomas', NULL, true),
  ('Luiza Gardenal Pires', NULL, true),
  ('Max Eisele', NULL, true),
  ('Julia Gardenal Pires', NULL, true),
  ('Michelle Koch', NULL, true),
  ('Grace Koch', NULL, true),
  ('Jordan Ross', NULL, true),
  ('Aidan Koch', NULL, true),
  ('Scott Koch', NULL, true),
  ('Carmen Lucia Gardenal', NULL, true),
  ('Araldo Fernandes Gardenal', NULL, true),
  ('Juliana Gardenal', NULL, true),
  ('Thiago Sforcin', NULL, true),
  ('Felipe Gardenal', NULL, true),
  ('Bianca Tineo Dias', NULL, true),
  ('Lucas Duarte', NULL, true),
  ('Milena Baliero', NULL, true),
  ('Lucas Bertolotti', NULL, true),
  ('Bernardo Baliero Bertolotti', 'pago', true),
  ('Rodrigo Manavello Gardenal', NULL, true),
  ('Ricardo Manavello Gardenal', NULL, true),
  ('Marcela Lavorenti', NULL, true),
  ('Julio Lavorenti Gardenal', 'pago', true),
  ('Margareth Manavello', NULL, true),
  ('Camila Mattos', NULL, true),
  ('Ana Beatriz Machado', NULL, true),
  ('Felipe Gusmão', NULL, true),
  ('Beatriz Tonche', NULL, true),
  ('Hikaru Teraguchi', NULL, true),
  ('Carolina Boaventura', NULL, true),
  ('Bruna Causo', NULL, true),
  ('Igor Menezes', NULL, true),
  ('Maria Isabelle Neves de Oliveira', NULL, true),
  ('Elias Jose Piazentin Gonçalves Junior', NULL, true),
  ('Thais Regina de Sene', NULL, true),
  ('Karoline Queiroz', NULL, true),
  ('Patrícia Yogui', NULL, true),
  ('Tatiane Neri', NULL, true),
  ('Rosangela Andretta', NULL, true),
  ('José Carlos Andretta', NULL, true),
  ('Isabella Toledo', NULL, true),
  ('Vitor Marquesim', NULL, true),
  ('Luan Manavello', NULL, true),
  ('Juliana Lavorenti', NULL, true),
  ('Deborah Pires', NULL, true),
  ('Ogney', NULL, false),
  ('Amanda Felix Camocardi', NULL, true),
  ('Patrick Leonardo', NULL, true),
  ('Gustavo Ferrari', NULL, true),
  ('Karen', NULL, true),
  ('Julio Bonatti', NULL, true),
  ('Giovanna Assuaga', NULL, true),
  ('Julio Bezerra', NULL, true),
  ('Renato Rangel', NULL, true),
  ('namorada Renato', NULL, false),
  ('Lucas Rangel', NULL, true),
  ('Nathalia de Oliveira Sellaris', NULL, true),
  ('Alexandre Sellaris', NULL, true),
  ('Heitor Sellaris', NULL, true),
  ('Larissa Ariana', NULL, true),
  ('Rafael Massad', NULL, true),
  ('Marcela Andrea', NULL, true),
  ('Fabio Lemos', NULL, true),
  ('Victor Yuri', NULL, true),
  ('Giulia Rosaneli', NULL, true),
  ('Athaan Januário', NULL, true),
  ('Icaro Vinicius Soares', NULL, true),
  ('Ariadny Sanches', NULL, true),
  ('Douglas Adilso Grolli', NULL, true),
  ('Pedro Andretta', NULL, true),
  ('Naiara Passos', NULL, true),
  ('Paulo Andretta', NULL, true),
  ('Luciane Vieira Andretta', NULL, true),
  ('Bruno Andretta', NULL, true),
  ('Adriana Naomi Ogura', NULL, true),
  ('Veluma Pires', NULL, true),
  ('Cleiton Pires', NULL, true),
  ('Theo Pires', 'pago', true),
  ('Ian Pires', 'pago', true),
  ('Camila Caroline Gonçalves de Pontes', NULL, true),
  ('banda1', NULL, false),
  ('banda2', NULL, false),
  ('banda 3', NULL, false),
  ('banda 4', NULL, false),
  ('banda 5', NULL, false),
  ('banda 6', NULL, false),
  ('banda 7', NULL, false);
